// characters.js - 24종 캐릭터 데이터

const CHARACTERS = [
    // ── 기본 (무료) ──────────────────────────────────────
    {
        id: 'chick',
        name: '삐약이',
        emoji: '🐥',
        color: '#FFD93D',
        bodyColor: '#FFD93D',
        eyeColor: '#333',
        blushColor: '#FFB347',
        desc: '기본 캐릭터! 귀여운 노란 병아리',
        price: 0,
        rarity: 'common',
    },
    // ── 일반 (50~100) ────────────────────────────────────
    {
        id: 'frog',
        name: '개구리군',
        emoji: '🐸',
        color: '#6BCB77',
        bodyColor: '#6BCB77',
        eyeColor: '#fff',
        blushColor: '#A8E6A3',
        desc: '폴짝폴짝! 점프의 달인',
        price: 50,
        rarity: 'common',
    },
    {
        id: 'bunny',
        name: '토순이',
        emoji: '🐰',
        color: '#FFB3DE',
        bodyColor: '#FFB3DE',
        eyeColor: '#FF6B9D',
        blushColor: '#FF99C8',
        desc: '귀가 쫑긋한 사랑스러운 토끼',
        price: 50,
        rarity: 'common',
    },
    {
        id: 'cat',
        name: '냥이',
        emoji: '🐱',
        color: '#FFA07A',
        bodyColor: '#FFA07A',
        eyeColor: '#4DB6AC',
        blushColor: '#FFCC80',
        desc: '냐옹~ 도도한 고양이',
        price: 60,
        rarity: 'common',
    },
    {
        id: 'dog',
        name: '멍멍이',
        emoji: '🐶',
        color: '#C8A97E',
        bodyColor: '#C8A97E',
        eyeColor: '#5D4037',
        blushColor: '#FFAB91',
        desc: '꼬리 흔드는 귀여운 강아지',
        price: 60,
        rarity: 'common',
    },
    {
        id: 'hamster',
        name: '햄스터',
        emoji: '🐹',
        color: '#F4A261',
        bodyColor: '#F4A261',
        eyeColor: '#333',
        blushColor: '#FFCBA4',
        desc: '볼이 빵빵한 햄스터',
        price: 70,
        rarity: 'common',
    },
    {
        id: 'duck',
        name: '오리야',
        emoji: '🦆',
        color: '#81D4FA',
        bodyColor: '#B0E57C',
        eyeColor: '#333',
        blushColor: '#81D4FA',
        desc: '꽥꽥! 물을 좋아하는 오리',
        price: 70,
        rarity: 'common',
    },
    {
        id: 'pig',
        name: '꿀꿀이',
        emoji: '🐷',
        color: '#FFB6C1',
        bodyColor: '#FFB6C1',
        eyeColor: '#E91E63',
        blushColor: '#FF8FAB',
        desc: '꿀꿀~ 분홍 코가 귀여운 돼지',
        price: 80,
        rarity: 'common',
    },
    {
        id: 'penguin',
        name: '펭귄군',
        emoji: '🐧',
        color: '#37474F',
        bodyColor: '#37474F',
        eyeColor: '#fff',
        blushColor: '#FF7043',
        desc: '뒤뚱뒤뚱 귀여운 펭귄',
        price: 80,
        rarity: 'common',
    },
    {
        id: 'bear',
        name: '곰돌이',
        emoji: '🐻',
        color: '#795548',
        bodyColor: '#795548',
        eyeColor: '#333',
        blushColor: '#FFAB91',
        desc: '따뜻하고 포근한 곰돌이',
        price: 90,
        rarity: 'common',
    },
    {
        id: 'koala',
        name: '코알라',
        emoji: '🐨',
        color: '#90A4AE',
        bodyColor: '#90A4AE',
        eyeColor: '#333',
        blushColor: '#B0BEC5',
        desc: '나뭇잎을 사랑하는 코알라',
        price: 90,
        rarity: 'common',
    },
    {
        id: 'mouse',
        name: '쥐돌이',
        emoji: '🐭',
        color: '#BCAAA4',
        bodyColor: '#BCAAA4',
        eyeColor: '#F06292',
        blushColor: '#F8BBD0',
        desc: '뾰족한 귀가 매력인 생쥐',
        price: 100,
        rarity: 'common',
    },
    // ── 레어 (150~250) ───────────────────────────────────
    {
        id: 'fox',
        name: '여우님',
        emoji: '🦊',
        color: '#FF6D00',
        bodyColor: '#FF6D00',
        eyeColor: '#333',
        blushColor: '#FFAB40',
        desc: '약삭빠른 오렌지 여우',
        price: 150,
        rarity: 'rare',
    },
    {
        id: 'panda',
        name: '판다야',
        emoji: '🐼',
        color: '#fff',
        bodyColor: '#fff',
        eyeColor: '#212121',
        blushColor: '#FFCDD2',
        desc: '흑백의 귀여움 끝판왕',
        price: 150,
        rarity: 'rare',
    },
    {
        id: 'tiger',
        name: '호랑이',
        emoji: '🐯',
        color: '#FF8F00',
        bodyColor: '#FF8F00',
        eyeColor: '#333',
        blushColor: '#FFD54F',
        desc: '줄무늬가 멋진 아기 호랑이',
        price: 180,
        rarity: 'rare',
    },
    {
        id: 'wolf',
        name: '늑대군',
        emoji: '🐺',
        color: '#78909C',
        bodyColor: '#78909C',
        eyeColor: '#fff',
        blushColor: '#90A4AE',
        desc: '늠름하지만 사실 겁쟁이',
        price: 180,
        rarity: 'rare',
    },
    {
        id: 'raccoon',
        name: '너구리',
        emoji: '🦝',
        color: '#9E9E9E',
        bodyColor: '#9E9E9E',
        eyeColor: '#333',
        blushColor: '#BDBDBD',
        desc: '도시의 밤을 누비는 너구리',
        price: 200,
        rarity: 'rare',
    },
    {
        id: 'monkey',
        name: '원숭이',
        emoji: '🐵',
        color: '#A1887F',
        bodyColor: '#A1887F',
        eyeColor: '#333',
        blushColor: '#FFAB91',
        desc: '바나나를 좋아하는 장난꾸러기',
        price: 200,
        rarity: 'rare',
    },
    {
        id: 'sheep',
        name: '양순이',
        emoji: '🐑',
        color: '#ECEFF1',
        bodyColor: '#ECEFF1',
        eyeColor: '#333',
        blushColor: '#FFD0D0',
        desc: '폭신폭신 구름 같은 양',
        price: 220,
        rarity: 'rare',
    },
    {
        id: 'owl',
        name: '부엉이',
        emoji: '🦉',
        color: '#8D6E63',
        bodyColor: '#8D6E63',
        eyeColor: '#FFF59D',
        blushColor: '#A1887F',
        desc: '지혜로운 눈을 가진 부엉이',
        price: 250,
        rarity: 'rare',
    },
    // ── 에픽 (350~500) ───────────────────────────────────
    {
        id: 'unicorn',
        name: '유니콘',
        emoji: '🦄',
        color: '#CE93D8',
        bodyColor: '#CE93D8',
        eyeColor: '#AB47BC',
        blushColor: '#F8BBD0',
        desc: '무지개빛 뿔을 가진 환상의 동물',
        price: 350,
        rarity: 'epic',
    },
    {
        id: 'dragon',
        name: '드래곤',
        emoji: '🐲',
        color: '#4CAF50',
        bodyColor: '#4CAF50',
        eyeColor: '#F44336',
        blushColor: '#A5D6A7',
        desc: '불을 뿜는 아기 드래곤',
        price: 400,
        rarity: 'epic',
    },
    {
        id: 'alien',
        name: '외계인',
        emoji: '👽',
        color: '#B2DFDB',
        bodyColor: '#B2DFDB',
        eyeColor: '#00BCD4',
        blushColor: '#80CBC4',
        desc: '멀리서 온 신비로운 외계인',
        price: 450,
        rarity: 'epic',
    },
    {
        id: 'robot',
        name: '로봇군',
        emoji: '🤖',
        color: '#90CAF9',
        bodyColor: '#90CAF9',
        eyeColor: '#F44336',
        blushColor: '#64B5F6',
        desc: '삐빅- 최첨단 귀요미 로봇',
        price: 500,
        rarity: 'epic',
    },
];

const RARITY_COLOR = {
    common: { bg: '#4a5568', text: '#a0aec0', label: 'NORMAL' },
    rare: { bg: '#1a365d', text: '#63b3ed', label: 'RARE' },
    epic: { bg: '#44337a', text: '#d6bcfa', label: 'EPIC' },
};
