// 100개의 인형 데이터
const DOLLS_DATA = [
  // 기본 등급 (1-50) - 4개 이미지 순환 사용
  { id: 1, name: "토끼 인형", rarity: "common", image: "assets/dolls/individual/common_bunny.png" },
  { id: 2, name: "곰 인형", rarity: "common", image: "assets/dolls/individual/common_bear.png" },
  { id: 3, name: "고양이 인형", rarity: "common", image: "assets/dolls/individual/common_cat.png" },
  { id: 4, name: "강아지 인형", rarity: "common", image: "assets/dolls/individual/common_dog.png" },
  { id: 5, name: "토끼 인형", rarity: "common", image: "assets/dolls/individual/common_bunny.png" },
  { id: 6, name: "곰 인형", rarity: "common", image: "assets/dolls/individual/common_bear.png" },
  { id: 7, name: "고양이 인형", rarity: "common", image: "assets/dolls/individual/common_cat.png" },
  { id: 8, name: "강아지 인형", rarity: "common", image: "assets/dolls/individual/common_dog.png" },
  { id: 9, name: "토끼 인형", rarity: "common", image: "assets/dolls/individual/common_bunny.png" },
  { id: 10, name: "곰 인형", rarity: "common", image: "assets/dolls/individual/common_bear.png" },
  { id: 11, name: "고양이 인형", rarity: "common", image: "assets/dolls/individual/common_cat.png" },
  { id: 12, name: "강아지 인형", rarity: "common", image: "assets/dolls/individual/common_dog.png" },
  { id: 13, name: "토끼 인형", rarity: "common", image: "assets/dolls/individual/common_bunny.png" },
  { id: 14, name: "곰 인형", rarity: "common", image: "assets/dolls/individual/common_bear.png" },
  { id: 15, name: "고양이 인형", rarity: "common", image: "assets/dolls/individual/common_cat.png" },
  { id: 16, name: "강아지 인형", rarity: "common", image: "assets/dolls/individual/common_dog.png" },
  { id: 17, name: "토끼 인형", rarity: "common", image: "assets/dolls/individual/common_bunny.png" },
  { id: 18, name: "곰 인형", rarity: "common", image: "assets/dolls/individual/common_bear.png" },
  { id: 19, name: "고양이 인형", rarity: "common", image: "assets/dolls/individual/common_cat.png" },
  { id: 20, name: "강아지 인형", rarity: "common", image: "assets/dolls/individual/common_dog.png" },
  { id: 21, name: "토끼 인형", rarity: "common", image: "assets/dolls/individual/common_bunny.png" },
  { id: 22, name: "곰 인형", rarity: "common", image: "assets/dolls/individual/common_bear.png" },
  { id: 23, name: "고양이 인형", rarity: "common", image: "assets/dolls/individual/common_cat.png" },
  { id: 24, name: "강아지 인형", rarity: "common", image: "assets/dolls/individual/common_dog.png" },
  { id: 25, name: "토끼 인형", rarity: "common", image: "assets/dolls/individual/common_bunny.png" },
  { id: 26, name: "곰 인형", rarity: "common", image: "assets/dolls/individual/common_bear.png" },
  { id: 27, name: "고양이 인형", rarity: "common", image: "assets/dolls/individual/common_cat.png" },
  { id: 28, name: "강아지 인형", rarity: "common", image: "assets/dolls/individual/common_dog.png" },
  { id: 29, name: "토끼 인형", rarity: "common", image: "assets/dolls/individual/common_bunny.png" },
  { id: 30, name: "곰 인형", rarity: "common", image: "assets/dolls/individual/common_bear.png" },
  { id: 31, name: "고양이 인형", rarity: "common", image: "assets/dolls/individual/common_cat.png" },
  { id: 32, name: "강아지 인형", rarity: "common", image: "assets/dolls/individual/common_dog.png" },
  { id: 33, name: "토끼 인형", rarity: "common", image: "assets/dolls/individual/common_bunny.png" },
  { id: 34, name: "곰 인형", rarity: "common", image: "assets/dolls/individual/common_bear.png" },
  { id: 35, name: "고양이 인형", rarity: "common", image: "assets/dolls/individual/common_cat.png" },
  { id: 36, name: "강아지 인형", rarity: "common", image: "assets/dolls/individual/common_dog.png" },
  { id: 37, name: "토끼 인형", rarity: "common", image: "assets/dolls/individual/common_bunny.png" },
  { id: 38, name: "곰 인형", rarity: "common", image: "assets/dolls/individual/common_bear.png" },
  { id: 39, name: "고양이 인형", rarity: "common", image: "assets/dolls/individual/common_cat.png" },
  { id: 40, name: "강아지 인형", rarity: "common", image: "assets/dolls/individual/common_dog.png" },
  { id: 41, name: "토끼 인형", rarity: "common", image: "assets/dolls/individual/common_bunny.png" },
  { id: 42, name: "곰 인형", rarity: "common", image: "assets/dolls/individual/common_bear.png" },
  { id: 43, name: "고양이 인형", rarity: "common", image: "assets/dolls/individual/common_cat.png" },
  { id: 44, name: "강아지 인형", rarity: "common", image: "assets/dolls/individual/common_dog.png" },
  { id: 45, name: "토끼 인형", rarity: "common", image: "assets/dolls/individual/common_bunny.png" },
  { id: 46, name: "곰 인형", rarity: "common", image: "assets/dolls/individual/common_bear.png" },
  { id: 47, name: "고양이 인형", rarity: "common", image: "assets/dolls/individual/common_cat.png" },
  { id: 48, name: "강아지 인형", rarity: "common", image: "assets/dolls/individual/common_dog.png" },
  { id: 49, name: "토끼 인형", rarity: "common", image: "assets/dolls/individual/common_bunny.png" },
  { id: 50, name: "곰 인형", rarity: "common", image: "assets/dolls/individual/common_bear.png" },

  // 레어 등급 (51-80) - 3개 이미지 순환 사용
  { id: 51, name: "황금 여우", rarity: "rare", image: "assets/dolls/individual/rare_fox.png" },
  { id: 52, name: "황금 팬더", rarity: "rare", image: "assets/dolls/individual/rare_panda.png" },
  { id: 53, name: "황금 펭귄", rarity: "rare", image: "assets/dolls/individual/rare_penguin.png" },
  { id: 54, name: "황금 여우", rarity: "rare", image: "assets/dolls/individual/rare_fox.png" },
  { id: 55, name: "황금 팬더", rarity: "rare", image: "assets/dolls/individual/rare_panda.png" },
  { id: 56, name: "황금 펭귄", rarity: "rare", image: "assets/dolls/individual/rare_penguin.png" },
  { id: 57, name: "황금 여우", rarity: "rare", image: "assets/dolls/individual/rare_fox.png" },
  { id: 58, name: "황금 팬더", rarity: "rare", image: "assets/dolls/individual/rare_panda.png" },
  { id: 59, name: "황금 펭귄", rarity: "rare", image: "assets/dolls/individual/rare_penguin.png" },
  { id: 60, name: "황금 여우", rarity: "rare", image: "assets/dolls/individual/rare_fox.png" },
  { id: 61, name: "크리스탈 팬더", rarity: "rare", image: "assets/dolls/individual/rare_panda.png" },
  { id: 62, name: "크리스탈 펭귄", rarity: "rare", image: "assets/dolls/individual/rare_penguin.png" },
  { id: 63, name: "크리스탈 여우", rarity: "rare", image: "assets/dolls/individual/rare_fox.png" },
  { id: 64, name: "크리스탈 팬더", rarity: "rare", image: "assets/dolls/individual/rare_panda.png" },
  { id: 65, name: "크리스탈 펭귄", rarity: "rare", image: "assets/dolls/individual/rare_penguin.png" },
  { id: 66, name: "크리스탈 여우", rarity: "rare", image: "assets/dolls/individual/rare_fox.png" },
  { id: 67, name: "크리스탈 팬더", rarity: "rare", image: "assets/dolls/individual/rare_panda.png" },
  { id: 68, name: "크리스탈 펭귄", rarity: "rare", image: "assets/dolls/individual/rare_penguin.png" },
  { id: 69, name: "크리스탈 여우", rarity: "rare", image: "assets/dolls/individual/rare_fox.png" },
  { id: 70, name: "크리스탈 팬더", rarity: "rare", image: "assets/dolls/individual/rare_panda.png" },
  { id: 71, name: "네온 펭귄", rarity: "rare", image: "assets/dolls/individual/rare_penguin.png" },
  { id: 72, name: "네온 여우", rarity: "rare", image: "assets/dolls/individual/rare_fox.png" },
  { id: 73, name: "네온 팬더", rarity: "rare", image: "assets/dolls/individual/rare_panda.png" },
  { id: 74, name: "네온 펭귄", rarity: "rare", image: "assets/dolls/individual/rare_penguin.png" },
  { id: 75, name: "네온 여우", rarity: "rare", image: "assets/dolls/individual/rare_fox.png" },
  { id: 76, name: "네온 팬더", rarity: "rare", image: "assets/dolls/individual/rare_panda.png" },
  { id: 77, name: "네온 펭귄", rarity: "rare", image: "assets/dolls/individual/rare_penguin.png" },
  { id: 78, name: "네온 여우", rarity: "rare", image: "assets/dolls/individual/rare_fox.png" },
  { id: 79, name: "네온 팬더", rarity: "rare", image: "assets/dolls/individual/rare_panda.png" },
  { id: 80, name: "네온 펭귄", rarity: "rare", image: "assets/dolls/individual/rare_penguin.png" },

  // 슈퍼레어 등급 (81-95) - 2개 이미지 순환 사용
  { id: 81, name: "은하수 유니콘", rarity: "super_rare", image: "assets/dolls/individual/super_rare_unicorn.png" },
  { id: 82, name: "은하수 드래곤", rarity: "super_rare", image: "assets/dolls/individual/super_rare_dragon.png" },
  { id: 83, name: "은하수 유니콘", rarity: "super_rare", image: "assets/dolls/individual/super_rare_unicorn.png" },
  { id: 84, name: "은하수 드래곤", rarity: "super_rare", image: "assets/dolls/individual/super_rare_dragon.png" },
  { id: 85, name: "은하수 유니콘", rarity: "super_rare", image: "assets/dolls/individual/super_rare_unicorn.png" },
  { id: 86, name: "은하수 드래곤", rarity: "super_rare", image: "assets/dolls/individual/super_rare_dragon.png" },
  { id: 87, name: "은하수 유니콘", rarity: "super_rare", image: "assets/dolls/individual/super_rare_unicorn.png" },
  { id: 88, name: "은하수 드래곤", rarity: "super_rare", image: "assets/dolls/individual/super_rare_dragon.png" },
  { id: 89, name: "은하수 유니콘", rarity: "super_rare", image: "assets/dolls/individual/super_rare_unicorn.png" },
  { id: 90, name: "은하수 드래곤", rarity: "super_rare", image: "assets/dolls/individual/super_rare_dragon.png" },
  { id: 91, name: "은하수 유니콘", rarity: "super_rare", image: "assets/dolls/individual/super_rare_unicorn.png" },
  { id: 92, name: "은하수 드래곤", rarity: "super_rare", image: "assets/dolls/individual/super_rare_dragon.png" },
  { id: 93, name: "은하수 유니콘", rarity: "super_rare", image: "assets/dolls/individual/super_rare_unicorn.png" },
  { id: 94, name: "은하수 드래곤", rarity: "super_rare", image: "assets/dolls/individual/super_rare_dragon.png" },
  { id: 95, name: "은하수 유니콘", rarity: "super_rare", image: "assets/dolls/individual/super_rare_unicorn.png" },

  // 시크릿 등급 (96-100) - 1개 이미지 사용
  { id: 96, name: "레인보우 유니콘", rarity: "secret", image: "assets/dolls/individual/secret_rainbow.png" },
  { id: 97, name: "레인보우 페가수스", rarity: "secret", image: "assets/dolls/individual/secret_rainbow.png" },
  { id: 98, name: "레인보우 피닉스", rarity: "secret", image: "assets/dolls/individual/secret_rainbow.png" },
  { id: 99, name: "레인보우 드래곤", rarity: "secret", image: "assets/dolls/individual/secret_rainbow.png" },
  { id: 100, name: "레인보우 엔젤", rarity: "secret", image: "assets/dolls/individual/secret_rainbow.png" }
];

// 등급별 확률
const RARITY_WEIGHTS = {
  common: 60,
  rare: 25,
  super_rare: 12,
  secret: 3
};
